export enum AppCodes {
  OPERATION_SUCCESS = 'OPERATION_SUCCESS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  USER_CREATED = 'USER_CREATED',
  BAD_REQUEST = 'BAD_REQUEST',
}
