export enum ValidationErrorCode {
  REQUIRED = 'REQUIRED',
  MIN_LENGTH = 'MIN_LENGTH',
  MAX_LENGTH = 'MAX_LENGTH',
  SHOULD_BE_AN_EMAIL = 'SHOULD_BE_AN_EMAIL',
  INVALID_TYPE = 'INVALID_TYPE',
  INVALID_FORMAT = 'INVALID_FORMAT',
  UNKNOWN = 'UNKNOWN',
}
