apiVersion: v1
kind: Service
metadata:
  name: url-shortener-api-service
  namespace: url-shortener-stack
spec:
  type: LoadBalancer
  selector:
    app: url-shortener-api
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
